

service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
stage: prod
region: eu-west-1


functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    timeout: 60 #seconds
    memorySize: 128 #mb
