

service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x
stage: dev
region: eu-west-1
timeout: 60 #seconds
memorySize: 128 #mb



functions:
  hello:
    handler: src/handler.generateRandomNumber
